name: build-windows-msys2
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up MSYS2 (MINGW64)
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-gnucobol
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-binutils
            pkgconf
            zip
            awk
            sed
            findutils

      - name: Build (cobc drives gcc)
        shell: msys2 {0}
        run: |
          set -euxo pipefail
          export PKG_CONFIG_PATH=/mingw64/lib/pkgconfig
          cobc -x -free -O3 -flto \
            main.cob sdl_expose.c \
            $(pkgconf --cflags --libs sdl2)
          mv a.exe burn_ship.exe || true

      - name: Bundle runtime DLLs (objdump-based)
        shell: msys2 {0}
        run: |
          set -euxo pipefail
          mkdir -p dist
          cp burn_ship.exe dist/

          # List dependent DLL names from the PE headers
          DLLS=$(objdump -p dist/burn_ship.exe | awk '/DLL Name:/ {print $3}')
          for dll in $DLLS; do
            # Try common locations
            for root in /mingw64/bin /usr/bin; do
              if [ -f "$root/$dll" ]; then
                cp -n "$root/$dll" dist/
                break
              fi
            done
          done

          # Safety net: ensure core DLLs are present
          cp -n /mingw64/bin/SDL2.dll dist/ || true
          ls /mingw64/bin/libcob-*.dll | head -n1 | xargs -I{} cp -n {} dist/ || true

          # Record tool versions for reproducibility
          pkgconf --modversion sdl2 > dist/VERSIONS.txt
          cobc -v >> dist/VERSIONS.txt
          gcc --version | head -n1 >> dist/VERSIONS.txt

          (cd dist && zip -9r ../burn_ship_win64.zip .)

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: burn_ship_win64
          path: burn_ship_win64.zip
          retention-days: 90
